version: '3'

services:
  node:
    build:
      context: .
    image:
      build-docker-mid-server:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - .env
    