version: '3'

services:
  mid-server:
    build:
      context: .
      args: 
        URL: https://install.service-now.com/glide/distribution/builds/package/app-signed/mid/2020/08/05/mid.newyork-06-26-2019__patch10-07-30-2020_08-05-2020_0901.linux.x86-64.zip
    env_file:
      - .env
    restart: 
      always
