version: '3'

services:
  mid-server:
    build:
      context: .
      args: 
        URL: https://install.service-now.com/glide/distribution/builds/package/mid/2019/09/06/mid.london-06-27-2018__patch10-08-28-2019_09-06-2019_0928.linux.x86-64.zip
    env_file:
      - .env
    restart: 
      always
